### ISSUE TITLE
Example project

### ISSUE THREAD

**Issue by jeropanda** [one-signal/OneSignal-Unity-SDK#2]
error : Main manifest has <uses-sdk android:targetSdkVersion='22'> but library uses targetSdkVersion='23'

I just opened and tried to build the example project.

got no idea why I am having errors.

using unity 5

**Comment by Guhanesh** [comment]
Open SDK Manager.exe in Android SDK. Install API 23(Android 6.0) SDK Platform.Now build.

**Comment by jeropanda** [comment]
[http://i.imgur.com/BvOOtvI.png](url)

i already installed it but still having the error:

OneSignal-Unity-SDK-master/Unity5OneSignalExample/Temp/StagingArea/android-libraries/onesignal-unity/AndroidManifest.xml:3] Main manifest has <uses-sdk android:targetSdkVersion='22'> but library uses targetSdkVersion='23'

**Comment by Guhanesh** [comment]
404 error in the image url. @jeropanda

**Comment by jeropanda** [comment]
http://imgur.com/BvOOtvI

here's the pic, I have installed the latest API 23(Android 6.0) SDK Platform

but still getting the error

> OneSignal-Unity-SDK-master/Unity5OneSignalExample/Temp/StagingArea/android-libraries/onesignal-unity/AndroidManifest.xml:3] Main manifest has but library uses targetSdkVersion='23'

**Comment by jkasten2** [comment]
Sorry about the regression bug, the entry was creating an issue where all target entries in every `AndroidManifest.xml` would have to match.

We just removed the API target entry from our sdk in version [1.13.2](https://github.com/one-signal/OneSignal-Unity-SDK/releases/tag/1.13.2) to fix this.

Thanks.
