### ISSUE TITLE
strange simple "text" Android notification after every notification from OneSignal

### ISSUE THREAD

**Issue by BloodJohn** [one-signal/OneSignal-Unity-SDK#3]
After about 18 March, we started getting two notifications at a time.

https://monosnap.com/image/H84AJTIhpSPN19IPWC8F1xDBEWHgQS

bonjure - normal notification
miracle mach 3, text - strange notification

In addition to notification with the selected images and text filled in OneSignal, the device comes notification with the text "text", title "Miracle Match 3" and the image of the application shortcut (for android 5+ definltely image notification) http://take.ms/btQ1d

This may not be a local notification from Unity app, because our local notification is recorded with the correct icons (not white square, as here)

And clicking on this notification opens the app.

log from device (different notification "Content 8"):

03-23 15:30:21.914: D/DhcpClient(779): Received packet: ec:35:86:d5:c6:df ACK: your new IP /192.168.15.189, netmask /255.255.254.0, gateways [/192.168.15.254] DNS servers: /192.168.15.12 /192.168.15.13 , lease time 691200
03-23 15:30:29.392: D/NetlinkSocketObserver(779): NeighborEvent{elapsedMs=99936974, 192.168.15.254, [6805CA247CA2], RTM_NEWNEIGH, NUD_STALE}
03-23 15:30:34.195: D/ConnectivityService(779): notifyType CAP_CHANGED for NetworkAgentInfo [WIFI () - 138]
03-23 15:30:37.912: D/NetlinkSocketObserver(779): NeighborEvent{elapsedMs=99945494, 192.168.15.254, [6805CA247CA2], RTM_NEWNEIGH, NUD_REACHABLE}
03-23 15:30:40.257: D/ConnectivityService(779): notifyType CAP_CHANGED for NetworkAgentInfo [WIFI () - 138]
03-23 15:30:52.418: D/ConnectivityService(779): notifyType CAP_CHANGED for NetworkAgentInfo [WIFI () - 138]
03-23 15:30:53.586: I/GCM(1232): GCM message com.playflock.fairytale 0:1458649853159956%9f79e73df9fd7ecd
03-23 15:30:53.618: V/GCMBroadcastReceiver(11267): onReceive: com.google.android.c2dm.intent.RECEIVE
03-23 15:30:53.618: V/UnityGCMBroadcastReceiver(11267): getGCMIntentServcieClassName
03-23 15:30:53.618: V/GCMBroadcastReceiver(11267): GCM IntentService class: com.kskkbys.unitygcmplugin.UnityGCMIntentService
03-23 15:30:53.618: V/GCMBaseIntentService(11267): Acquiring wakelock
03-23 15:30:53.621: V/GCMBaseIntentService(11267): Intent service name: GCMIntentService-DynamicSenderIds-3
03-23 15:30:53.625: V/UnityGCMIntentService(11267): onMessage
03-23 15:30:53.625: V/UnityGCMIntentService(11267): custom: {"i":"771de9f1-1f77-4c9f-9621-1d95d971618c"}
03-23 15:30:53.625: V/UnityGCMIntentService(11267): from: 186097931313
03-23 15:30:53.625: V/UnityGCMIntentService(11267): alert: ?? Content 8
03-23 15:30:53.625: V/UnityGCMIntentService(11267): title: ? Title 8
03-23 15:30:53.625: V/UnityGCMIntentService(11267): collapse_key: do_not_collapse
03-23 15:30:53.633: V/UnityGCMNotificationManager(11267): showNotification
03-23 15:30:53.637: V/NotificationService(779): pkg=com.playflock.fairytale canInterrupt=false intercept=true
03-23 15:30:53.651: V/GCMBaseIntentService(11267): Releasing wakelock
03-23 15:30:53.755: V/NotificationService(779): pkg=com.playflock.fairytale canInterrupt=false intercept=true
03-23 15:30:54.592: D/NetlinkSocketObserver(779): NeighborEvent{elapsedMs=99962174, 192.168.15.254, [6805CA247CA2], RTM_NEWNEIGH, NUD_STALE}
03-23 15:30:55.454: D/ConnectivityService(779): notifyType CAP_CHANGED for NetworkAgentInfo [WIFI () - 138]
03-23 15:31:07.780: D/NetlinkSocketObserver(779): NeighborEvent{elapsedMs=99975364, 192.168.15.254, [6805CA247CA2], RTM_NEWNEIGH, NUD_REACHABLE}
03-23 15:31:12.234: D/PhoneStatusBar(920): disable: < expand ICONS* alerts SYSTEM_INFO* back home recent clock search quick_settings >
03-23 15:31:12.286: D/DhcpClient(779): Received packet: 9c:fc:01:a5:31:95 ACK: your new IP /192.168.15.69, netmask /255.255.254.0, gateways [/192.168.15.254] DNS servers: /192.168.15.12 /192.168.15.13 , lease time 691200
03-23 15:31:12.360: I/MicroDetector(13382): Keeping mic open: false

**Comment by jkasten2** [comment]
Hello,

It appears that you have another GCM receiver that is displaying another notification from the OneSgnal GCM payload. Can you try removing `UnityGCMIntentService` from your app?

Thanks.

**Comment by BloodJohn** [comment]
Yes, as soon as I removed the "Android GCM Plugin" - the second notice was gone.

Thanks for the help.
