### ISSUE TITLE
[Unity] When I close my app from the task bar, no notifications are being received

### ISSUE THREAD

**Issue by peterwilli** [one-signal/OneSignal-Unity-SDK#4]
Hi,

I know this issue is already up there (but then for Cordova) but this is also more of a question.
I know that people said that you can't receive notifications when forcing the app to close (as in: moving it out of your task bar)

I don't get this, because how do other apps do it then? (like Whatsapp) which I also clearly close from my taskbar from time to time.

Is there a way to make sure the Unity SDK can do the same thing? A game is quite a big of a memory eating app and I can imagine users not wanting it to stay open just to receive a possible notification.

Thanks!

**Comment by jkasten2** [comment]
Hello,

Notification can still be received and displayed when the app has been closed normally. This includes it being killed by the OS to free RAM and a user swiping it away from the recent app list. On Android there is a "Force Stopped" state an app can be placed in but this can only happens in 2 cases.
* If the app is never opened after it has been installed. (Device won't be registered with OneSignal yet anyway.)
* It is force stopped from Settings>Apps.

See this answer for more details on the Android state.
http://stackoverflow.com/questions/20838415/gcm-push-notification-works-after-app-force-stop

Is the issue you're concerned about on iOS or Android?

Thanks.

**Comment by peterwilli** [comment]
It's on Android. When my app is put in the background (as in: pressing home button) there are no problems. I can still receive notifications. But if I remove it from the taskbar, notifications no longer appear.

**Comment by jkasten2** [comment]
@peterwilli It sounds like the Android ROM on the device you're using is putting the app in a "force stop" state when you do this. Could you let us know the exact Android version your testing on? We have seen Xiaomi devices do this before as they customize how the OS handles the closed state of apps.

Can you check the logcat when you send a notification after you swipe your app away?
I have a gist of a logcat that shows the difference between a normal close and a "force stop".
https://gist.github.com/jkasten2/fb83b1df754cf26df378
```
/** 2.2 Sent notification, GCM Message payload was received by Google Play services on the device. **/
02-27 13:44:54.019 2630-31453/? I/GCM: GCM message com.onesignal.example 0:1456609494311032%616610ddf9fd7ecd
/** 2.3 Google Play services couldn't wake the app as "result=CANCELLED" is in the intent callback. **/
02-27 13:44:54.044 2630-2630/? W/GCM-DMM: broadcast intent callback: result=CANCELLED forIntent { act=com.google.android.c2dm.intent.RECEIVE pkg=com.onesignal.example (has extras) }
```

**Comment by jkasten2** [comment]
@peterwilli We have found that Huawei devices also put apps into a "force stop" state when the app is swiped away from the recent apps list. Can you check the following if you have either of these brand devices?

App is closed on a Huawei or Xiaomi device due their custom Android tweaks.
* Huawei - Go to Settings > "Protected apps", check your app.
* Xiaomi - Make sure "Auto-start" property enabled for your app in the settings.


Also see [3. Notifications show successful but are not being shown](https://documentation.onesignal.com/docs/common-problems#3-notifications-show-successful-but-are-not-being-) on our site. We have added a few more details to it.

**Comment by peterwilli** [comment]
@jkasten2 Yeah I just was about to say the same thing. I have Xiaomi. It happened too with PushBullet. Not sure why whatsapp and gmail just work then.. Thanks again!
