### ISSUE TITLE
Xcode build error.

### ISSUE THREAD

**Issue by STAR-ZERO** [one-signal/OneSignal-Unity-SDK#5]
There was an error following when build in Xcode. 

```
Implicit conversion of non-Objective-C pointer type 'const char *' to 'NSString *` is disallowed with ARC
```

Problem code is this.
https://github.com/one-signal/OneSignal-Unity-SDK/blob/1.14.0/Unity5OneSignalExample%2FAssets%2FOneSignal%2FPlatforms%2FiOS%2FOneSignalUnityRuntime.m#L202

Correct code is as follows.

```objc
[oneSignal setEmail:[NSString stringWithUTF8String: email]];
```

#### Environment

* Unity 5.3.4
* Xcode 7.3

**Comment by jkasten2** [comment]
@STAR-ZERO thanks for reporting this. Just fixed it in our 1.14.1 release.
